stalwart_ldap_bind_password: ENC[AES256_GCM,data:xKABoYzUjCr2I8zmtkkckyTR4mo3FuZAa+8GdMq3D2+pt6uj+E+OWU9xo7DuaFJ1,iv:fZgZuy6RoiqgUrRXKiZNpCzPAnESMuhI1kJSa+Pn9wo=,tag:5Xsvm3rjbYGYwvn59ZS+9w==,type:str]
sops:
    age:
        - recipient: age1cnkpqa4lqwav6c4hptj7f2x0ct5ms9qts2mpcqs756nrjqdxt5nsg5v6ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMEhRNnV2K0pyVUZDckxT
            alMyTzdFNGlNTUtMaklVM0l2b3puNjlwZ1JvCmdQU0o4eDE4WGErVStGTCtLSnFu
            cW0xUWVKUG5kMzdaZE96Qit4L3NzcHMKLS0tIHEvU0o5anBBNkVkdzVNN3JWNnZ5
            eVZVcEtwRWxCWXNnL09DSURWOFZjY1UKTW8ZGb2E1IAAFwWfWSKgyYgtWZwWAdNA
            zanUuBYNWG+9s5ZYr3Jo0BWT4CohuL99weJ2biHc/zHR+MVWwxz5GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T15:53:26Z"
    mac: ENC[AES256_GCM,data:22z7YxAe4jeMjGugc11kYN/tyRqs33PKBtAXSRijgOZS/XToJUB5NOcb6E+6U11oB6A1QoWTdxs/i/jQjhxKg+Ed6rUbbd4MQBg5/3SluDq6LdbmdLnLhT2YHm1Y2AaqfoFKB2UI6OeLnKtcVZs0RX2EHjMHbrKFhsjSWG0k6N8=,iv:rLL3OogsfUXHtLebkCycCFgA5xLXixRfjRVhbUwptJg=,tag:EBtS3OERPJsUzJX5XdQriw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
