stalwart_ldap_bind_password: ENC[AES256_GCM,data:YvV7ZL/HPwjGJgL12u8tG6Unr+Qbw1fRtcrhPVJ7FCz1wE2ALf+G6nagoUBv8RDXJIH+s+y0b6M2LJeWePpDHdZlOBVfz7/JPKsCsrI0btX6ja9jDbSbkwHDNQ87tFijV4kKEQD2Bfwi9AX1xGmdDZG16LLKllZQjAIBkjnDlVdPmcizqRU74UGAL4D4kQzXxod+XidEB/nypKJP7EqE7egT8eAGg6sZCUZ0WV2iEjgk86OOjHgkMgmmFrIFLpJkTUKyZfSPP0nf2+KlcLRS7J6RZYo6T8GKbeBNCwMRPDgppRZfIvpsTd/+BW011aAtGf2EWaDLiTGKaaYfn/tp6NhERD22NETQTby2BCMd/dxCoiiNNVQSAPi5k5+5AV7C7ym5yoVV0NzyMetWIx0TRA6chX2OgzIO6sQPkuyYmBS2mEqybIhzT2838RRhSC2x8HFLeG+HZF43bqZW9JFYO8z4NxfrMQpPoBkeaP7aR9tir6B1O+ckPbdsgKActe1itsdGgQfIdG6I/XtYUNB0Vmz0OAV9dwHRWOg5nGc=,iv:AliX1+Li8pMlL2RcpCt2G7zt4v4Bk7jFtMvf+i37Wlk=,tag:rYA52U9xcWbKIbC3OakSZg==,type:str]
admin_password: ENC[AES256_GCM,data:j0HIP7mF5C+EYQ==,iv:Tn1jR98MPN1E6wV6x51RVLqhyCb9RZ5ThV6gqXdY/qw=,tag:V4hmNwiaMNkfaEbDl2aT3A==,type:str]
sops:
    age:
        - recipient: age1cnkpqa4lqwav6c4hptj7f2x0ct5ms9qts2mpcqs756nrjqdxt5nsg5v6ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMEhRNnV2K0pyVUZDckxT
            alMyTzdFNGlNTUtMaklVM0l2b3puNjlwZ1JvCmdQU0o4eDE4WGErVStGTCtLSnFu
            cW0xUWVKUG5kMzdaZE96Qit4L3NzcHMKLS0tIHEvU0o5anBBNkVkdzVNN3JWNnZ5
            eVZVcEtwRWxCWXNnL09DSURWOFZjY1UKTW8ZGb2E1IAAFwWfWSKgyYgtWZwWAdNA
            zanUuBYNWG+9s5ZYr3Jo0BWT4CohuL99weJ2biHc/zHR+MVWwxz5GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T09:15:26Z"
    mac: ENC[AES256_GCM,data:+qNY65tTnHT1kyf4llzGUKdA+FDJls9O8O5lnbsvdh4Ar6UZllLrK9iPWJgaV66D5eJ0+NcYrhMdMNOWd7XJ2SAkQYVM8uI65iVtFspmyFVrZc/GVxcqQu6QnIRFWuFZ5cqp21NXMGCg+sSbbGO5ZL99uiw//3xo/rVjOVHp/Do=,iv:krhdVpOCY7z/5ZZivqxcPLddfQuyOlpcDVdfmx5Wg2k=,tag:By7TVKYkliLgZg4+y757hw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
