stalwart_ldap_bind_password: ENC[AES256_GCM,data:YvV7ZL/HPwjGJgL12u8tG6Unr+Qbw1fRtcrhPVJ7FCz1wE2ALf+G6nagoUBv8RDXJIH+s+y0b6M2LJeWePpDHdZlOBVfz7/JPKsCsrI0btX6ja9jDbSbkwHDNQ87tFijV4kKEQD2Bfwi9AX1xGmdDZG16LLKllZQjAIBkjnDlVdPmcizqRU74UGAL4D4kQzXxod+XidEB/nypKJP7EqE7egT8eAGg6sZCUZ0WV2iEjgk86OOjHgkMgmmFrIFLpJkTUKyZfSPP0nf2+KlcLRS7J6RZYo6T8GKbeBNCwMRPDgppRZfIvpsTd/+BW011aAtGf2EWaDLiTGKaaYfn/tp6NhERD22NETQTby2BCMd/dxCoiiNNVQSAPi5k5+5AV7C7ym5yoVV0NzyMetWIx0TRA6chX2OgzIO6sQPkuyYmBS2mEqybIhzT2838RRhSC2x8HFLeG+HZF43bqZW9JFYO8z4NxfrMQpPoBkeaP7aR9tir6B1O+ckPbdsgKActe1itsdGgQfIdG6I/XtYUNB0Vmz0OAV9dwHRWOg5nGc=,iv:AliX1+Li8pMlL2RcpCt2G7zt4v4Bk7jFtMvf+i37Wlk=,tag:rYA52U9xcWbKIbC3OakSZg==,type:str]
sops:
    age:
        - recipient: age1cnkpqa4lqwav6c4hptj7f2x0ct5ms9qts2mpcqs756nrjqdxt5nsg5v6ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMEhRNnV2K0pyVUZDckxT
            alMyTzdFNGlNTUtMaklVM0l2b3puNjlwZ1JvCmdQU0o4eDE4WGErVStGTCtLSnFu
            cW0xUWVKUG5kMzdaZE96Qit4L3NzcHMKLS0tIHEvU0o5anBBNkVkdzVNN3JWNnZ5
            eVZVcEtwRWxCWXNnL09DSURWOFZjY1UKTW8ZGb2E1IAAFwWfWSKgyYgtWZwWAdNA
            zanUuBYNWG+9s5ZYr3Jo0BWT4CohuL99weJ2biHc/zHR+MVWwxz5GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T16:10:31Z"
    mac: ENC[AES256_GCM,data:fMZKZvQkwD2zZa4a6A1e2Nk1N5loengGla9U9kB/ARcjH2KJ2XS+wNy58zTZrOxjy6CtEmfkYtQFeqOm24VMiTTzEhB7epwlFcmnY4PnQwWVYv3SorccNtZpKuekzz46XNT9bIFCKnh9qVFWj0IDQdOZplYgSMrHop2NTCQysSQ=,iv:8r+miXk4G6YOUk3oNrG6Q/8fDZo4RYMWSH4sntuwHso=,tag:fbwBEDvpSsCK5quEZRTWGw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
