roundcube_client_secret: ENC[AES256_GCM,data:eb4PIS8nLxHf6VU675zjyiODqt4tmsFlRU4U4uwBIAgB4SmSOXgRCkAYW4c=,iv:bBh9cPM0oEil77bAT0IPwzRRL8m9vQo1p2mwOiDQX88=,tag:LG4cTKAUdm0Wat/soai6dQ==,type:str]
sops:
    age:
        - recipient: age1cnkpqa4lqwav6c4hptj7f2x0ct5ms9qts2mpcqs756nrjqdxt5nsg5v6ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMVFZQ2s0NFpKR241c1l2
            OHhDTUU3R2c4Tm1oZE9XWCtlVkVReXJlcVV3CjBoeE1ET3p2dnB1V0pYMkU5aWdj
            cW1wd09WRFI4UG01Um10dmVKNFo2dDAKLS0tIGYxZEQ0dk1NRDB2MlltcTJDNUpu
            SXNwRVR4aCtFUG9uWWRGbUlwR1R0c0kKnHBTkrulQMReIF/BdTxhvXbRNwqie9Rh
            CDnVU15GxxU4jj41W4bYEMQPjK7I6MQQlnaUBI/Ly+mvXoxwAeyPUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T18:26:58Z"
    mac: ENC[AES256_GCM,data:ezIbSchB+1eHAg1sIjMwF0jTJuZ5HWWwiY1pJpdLixF/LktXJyve9XOQLZpKtAc2wBC9Abr9qb8GiPgzEgp6mWA84vIApq/4MQWaT3Pm8i6aVqLUrSfF/r0sI0ajHbr3bmzr9NfJIphHctos0qIHdyF/Q0D/KH9e7Dudwlt5M48=,iv:BvBqLCliz9Ob1WkiBNcxeKL19MXYSIEflV1SxGS4F7I=,tag:UMJss4zDWSZVyWfoTkOaUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
